parameters:
#    feedler_user.example.class: Feedler\UserBundle\Example

services:
#    feedler_user.example:
#        class: %feedler_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
